name: 获取Telegram Chat ID

on:
  workflow_dispatch:

jobs:
  get-chat-id:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 获取 Chat ID
        run: |
          pip install requests
          python get_chat_id.py